### ISSUE TITLE
Issue with Safari 6.0.2 and Firefox 17.0

### ISSUE THREAD

**Issue by ghost** [weepy/jquery.path#18]
There seems to be some bezier path animation display bugs / inconsistencies with Safari 6.0.2 and Firefox 17.0. The animation renders smoothly in the latest build of Google Chrome but is jumpy and inconsistant in Safari and Firefox.

Here is the code I am using:

https://gist.github.com/4171190

Note: I am not 100% certain if the bug is originating in my bezier path code or if is definitely a browser compatibility bug.

Thanks,

Calvin

**Comment by weepy** [comment]
Path contains nothing that I can think would cause this.

Sent from my iPhone

On 29 Nov 2012, at 19:20, Calvin Stephens IV notifications@github.com
wrote:

There seems to be some bezier path animation display bugs / inconsistencies
with Safari 6.0.2 and Firefox 17.0. The animation renders smoothly in the
latest build of Google Chrome but is jumpy and inconsistant in Safari and
Firefox.

Here is the code I am using:

https://gist.github.com/4171190

Note: I am not 100% certain if the bug is originating in my bezier path
code or if is definitely a browser compatibility bug.

Thanks,

Calvin

—
Reply to this email directly or view it on
GitHubhttps://github.com/weepy/jquery.path/issues/18.

**Comment by ghost** [comment]
So it's possible that it's just an issue with Safari and Firefox?

**Comment by weepy** [comment]
yes most likely or jQuery working with these
